add_to_bot – STIM
add_to_bot Subroutine
7 statements
Source File
private subroutine add_to_bot(h, t, h2, t2)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: h
real(kind=rk), intent(in) :: t
real(kind=rk), intent(inout) :: h2
real(kind=rk), intent(inout) :: t2
Called by
Contents
None
Call graph
ice3lay_resize calls add_to_bot, even_up
even_up calls add_to_bot
do_stim_winton calls ice3lay_resize