do_stim_winton – STIM
do_stim_winton Subroutine
51 statements
Source File
public subroutine do_stim_winton(ice_cover, dz, dt, Tw, S, Ta, precip, Qsw, Qfluxes)
This SUBROUTINE updates the sea ice prognostic variables. The updated variables are upper ice layer temperature (T1), lower ice layer temperature (T2), snow thickness (hs), and ice thickness (hi).
The ice model performs this in two steps. First the temperatures are updated and secondly the changes in ice and snow thickness are calculated.
Any surplus energy that is not used for melting is returned in tmelt and bmelt.
Evaporation and bottom ablation formation are not included in this version of the model. Furthermore we do not keep an explicit water and salt budget for the sea ice and how that affects the water and salt budgets in the ocean.
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: ice_cover
real(kind=rk), intent(in) :: dz
real(kind=rk), intent(in) :: dt
real(kind=rk), intent(inout) :: Tw
real(kind=rk), intent(in) :: S
real(kind=rk), intent(in) :: Ta
real(kind=rk), intent(in) :: precip
real(kind=rk), intent(in) :: Qsw
private subroutine Qfluxes(T, qh, qe, qb)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: T
real(kind=rk), intent(out) :: qh
real(kind=rk), intent(out) :: qe
real(kind=rk), intent(out) :: qb
Calls
Contents
None
Call graph
do_stim_winton calls ice3lay_resize, ice3lay_temp, ice_optics
ice3lay_resize calls even_up, add_to_bot, add_to_top, e_to_melt
ice3lay_temp calls thm_checkout, e_to_melt
even_up calls add_to_bot, add_to_top