even_up – STIM
even_up Subroutine
18 statements
Source File
private subroutine even_up(h1, t1, h2, t2)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: h1
real(kind=rk), intent(inout) :: t1
real(kind=rk), intent(inout) :: h2
real(kind=rk), intent(inout) :: t2
Calls
Called by
Contents
None
Call graph
even_up calls add_to_bot, add_to_top
ice3lay_resize calls even_up
do_stim_winton calls ice3lay_resize