ice3lay_resize – STIM
ice3lay_resize Subroutine
103 statements
Source File
public subroutine ice3lay_resize(hs, hi, t1, t2, snow, frazil, evap, tmelt, bmelt, tfw, heat_to_ocn, h2o_to_ocn, h2o_from_ocn, snow_to_ice, bablt)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(inout) :: hs
real(kind=rk), intent(inout) :: hi
real(kind=rk), intent(inout) :: t1
real(kind=rk), intent(inout) :: t2
real(kind=rk), intent(in) :: snow
real(kind=rk), intent(in) :: frazil
real(kind=rk), intent(in) :: evap
real(kind=rk), intent(in) :: tmelt
real(kind=rk), intent(in) :: bmelt
real(kind=rk), intent(in) :: tfw
real(kind=rk), intent(out) :: heat_to_ocn
real(kind=rk), intent(out) :: h2o_to_ocn
real(kind=rk), intent(out) :: h2o_from_ocn
real(kind=rk), intent(out) :: snow_to_ice
real(kind=rk), intent(out), optional :: bablt
Calls
Called by
Contents
None
Call graph
ice3lay_resize calls e_to_melt, add_to_bot, even_up, add_to_top
even_up calls add_to_bot, add_to_top
do_stim_winton calls ice3lay_resize