ice3lay_temp – STIM
ice3lay_temp Subroutine
71 statements
Source File
public subroutine ice3lay_temp(hs, hi, t1, t2, ts, A, B, I, tfw, fb, dt, tmelt, bmelt)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: hs
real(kind=rk), intent(in) :: hi
real(kind=rk), intent(inout) :: t1
real(kind=rk), intent(inout) :: t2
real(kind=rk), intent(out) :: ts
real(kind=rk), intent(in) :: A
real(kind=rk), intent(in) :: B
real(kind=rk), intent(in) :: I
real(kind=rk), intent(in) :: tfw
real(kind=rk), intent(in) :: fb
real(kind=rk), intent(in) :: dt
real(kind=rk), intent(inout) :: tmelt
real(kind=rk), intent(inout) :: bmelt
Calls
Called by
Contents
None
Call graph
ice3lay_temp calls e_to_melt, thm_checkout
do_stim_winton calls ice3lay_temp