eat_init_pdaf – EAT
eat_init_pdaf Subroutine
36 statements
Source File
subroutine eat_init_pdaf()
Initialize EAT/PDAF component
Arguments
None
Calls
Called by
Contents
None
Call graph
eat_init_pdaf calls init_eat_config, mpi_recv, mpi_abort, init_pdaf
init_eat_config calls mpi_abort, mpi_comm_rank, mpi_comm_size, mpi_init, mpi_barrier, mpi_get_processor_name, mpi_comm_split
init_pdaf calls pdaf_init, pdaf_get_state, pdaf_set_comm_pdaf, pdaf_set_ens_pointer
eat_filter_pdaf calls eat_init_pdaf