eat_do_pdaf – EAT
eat_do_pdaf Subroutine
66 statements
Source File
subroutine eat_do_pdaf()
Get observations and states and do the PDAF/assimilation step
Arguments
None
Calls
Called by
Contents
None
Call graph
eat_do_pdaf calls mpi_waitall, mpi_isend, mpi_irecv, mpi_abort, assimilation_pdaf, mpi_recv
assimilation_pdaf calls pdaf_put_state_letkf, pdaf_put_state_3dvar, pdaf_put_state_enkf, pdaf_put_state_lseik, pdaf_put_state_etkf, pdaf_get_state, pdaf_force_analysis, pdaf_put_state_seik, pdaf_put_state_lestkf, pdaf_put_state_estkf
eat_filter_pdaf calls eat_do_pdaf