init_eat_config – EAT
init_eat_config Subroutine
131 statements
Source File
public subroutine init_eat_config(color)
Initialize MPI, define communicators and set variables
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: color
Calls
Called by
Contents
None
Call graph
init_eat_config calls mpi_comm_rank, mpi_comm_size, mpi_init, mpi_abort, mpi_barrier, mpi_get_processor_name, mpi_comm_split
eat_init_pdaf calls init_eat_config
eat_filter_pdaf calls eat_init_pdaf