init_pdaf – EAT
init_pdaf Subroutine
90 statements
Source File
public subroutine init_pdaf(EAT_COMM_filter, state_size, ensemble_size, model_states, stat)
Initialize various variable and call PDAF_init()
Arguments
Type Intent Optional Attributes Name
integer, intent(in), value :: EAT_COMM_filter
integer, intent(in), value :: state_size
integer, intent(in), value :: ensemble_size
real(kind=real64), pointer, contiguous :: model_states(:,:)
integer, intent(out) :: stat
Calls
Called by
Contents
None
Call graph
init_pdaf calls pdaf_init, pdaf_set_comm_pdaf, pdaf_set_ens_pointer, pdaf_get_state
eat_init_pdaf calls init_pdaf
eat_filter_pdaf calls eat_init_pdaf