UVic_ESCM_FABM – FABM in UVic
UVic_ESCM_FABM Program
GNU Free Documentation License
24 statements
Source File
Uses
uvic_fabm
uvic_common_blocks
Copyright (C) 2024 Bolding & Bruggeman
This program is used to assure that the sizes of arrays specified in size.h and the size deducted from fabm.yaml are in agreement.
Note
The way the include files are formatted does not allow to be included in F90 free format source code files.
Still to be solved is the issue of getting the variables in mw.h to double precission - for now mw.h in the base UVic source code folder has a kind=8 on all real arguments
An alternative method is to provide CMake with options to compile in 8 (4) byte. This is used for now - and no changes to mw.h are necessary
Calls
Variables
Type Attributes Name Initial
integer :: n
character(len=128) :: fname = 'fabm.yaml'
logical :: exists
Call graph
uvic_escm_fabm calls fabm_configure, fabm_list
fabm_configure calls fabm_create_model, set_bottom_index, set_domain, set_domain_start, set_domain_stop, set_mask
fabm_list calls bottom_state_variables, interior_state_variables, surface_state_variables