eat_filter_pdaf – EAT
eat_filter_pdaf Program
127 statements
Source File
Uses
pdaf_wrapper
eat_config
mpi
iso_fortran_env
A wrapper around the 'off_line PDAF' implmentation to keep it alive during ensemble simulations
Calls
Contents
Variables
nobs have_obs have_model state_size ensemble_size reqs stats model_states stderr stdout verbosity
Subroutines
eat_init_pdaf eat_do_pdaf eat_finish_pdaf
Variables
Type Attributes Name Initial
integer :: nobs = 0
logical :: have_obs = .true.
logical :: have_model = .true.
integer :: state_size
integer :: ensemble_size
integer, allocatable :: reqs(:)
integer, allocatable :: stats(:,:)
real(kind=real64), pointer, contiguous :: model_states(:,:)
integer, parameter :: stderr = error_unit
integer, parameter :: stdout = output_unit
integer :: verbosity = info
Subroutines
subroutine eat_init_pdaf()
Initialize EAT/PDAF component
Arguments
None
subroutine eat_do_pdaf()
Get observations and states and do the PDAF/assimilation step
Arguments
None
subroutine eat_finish_pdaf()
Cleanup and finalize the EAT/PDAF component
Arguments
None
Call graph
eat_filter_pdaf calls eat_init_pdaf, eat_do_pdaf, eat_finish_pdaf
eat_init_pdaf calls init_pdaf, mpi_abort, mpi_recv, init_eat_config
eat_do_pdaf calls mpi_waitall, mpi_irecv, mpi_isend, mpi_abort, assimilation_pdaf, mpi_recv
eat_finish_pdaf calls mpi_finalize, finish_pdaf
init_pdaf calls pdaf_get_state, pdaf_set_ens_pointer, pdaf_set_comm_pdaf, pdaf_init
assimilation_pdaf calls pdaf_get_state, pdaf_put_state_3dvar, pdaf_put_state_letkf, pdaf_put_state_enkf, pdaf_put_state_etkf, pdaf_force_analysis, pdaf_put_state_seik, pdaf_put_state_estkf, pdaf_put_state_lseik, pdaf_put_state_lestkf
init_eat_config calls mpi_abort, mpi_comm_rank, mpi_comm_size, mpi_barrier, mpi_get_processor_name, mpi_comm_split, mpi_init