format_real – Fortran Program
format_real Function
25 statements
Source File
private function format_real(value) result(string)
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in) :: value
Return Value character(len=:), allocatable
Called by
Contents
None
Call graph
real_get_comment calls format_real
real_as_string calls format_real
real_write_schema calls format_real