is_whitespace – Fortran Program
is_whitespace Function
4 statements
Source File
private function is_whitespace(string)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: string
Return Value logical
Called by
Contents
None
Call graph
next_line calls is_whitespace
find_mapping_character calls is_whitespace
read_value calls find_mapping_character, read_value, read_key_value_pair
read_key_value_pair calls read_value
parse calls read_value
test_yaml calls parse