read_key_value_pair – Fortran Program
read_key_value_pair Function
22 statements
Source File
private recursive function read_key_value_pair(file, icolon, icolon_stop) result(pair)
Arguments
Type Intent Optional Attributes Name
class(type_file), intent(inout) :: file
integer, intent(in) :: icolon
integer, intent(in) :: icolon_stop
Return Value type(type_key_value_pair)
Calls
Called by
Contents
None
Call graph
read_key_value_pair calls read_value
read_value calls read_key_value_pair, read_value, find_mapping_character
find_mapping_character calls is_whitespace
parse calls read_value
test_yaml calls parse