read_value – Fortran Program
read_value Function
60 statements
Source File
private recursive function read_value(file) result(node)
Arguments
Type Intent Optional Attributes Name
class(type_file), intent(inout) :: file
Return Value class(type_node), pointer
Calls
Called by
Contents
None
Call graph
read_value calls read_value, read_key_value_pair, find_mapping_character
read_key_value_pair calls read_value
find_mapping_character calls is_whitespace
parse calls read_value
test_yaml calls parse