real_set_data – Fortran Program
real_set_data Subroutine
14 statements
Source File
private subroutine real_set_data(self, backing_store_node)
Arguments
Type Intent Optional Attributes Name
class(type_real_setting), intent(inout) :: self
class(type_yaml_node), intent(in) :: backing_store_node
Calls
Called by
Contents
None
Call graph
real_set_data calls report_error
type_real_setting_create calls real_set_data
get_real2 calls type_real_setting_create