type_real_setting_create – Fortran Program
type_real_setting_create Function
37 statements
Source File
public function type_real_setting_create(node, target, long_name, units, default, minimum, maximum, description) result(setting)
Arguments
Type Intent Optional Attributes Name
class(type_settings_node), intent(inout) :: node
real(kind=rk), target :: target
character(len=*), intent(in) :: long_name
character(len=*), intent(in) :: units
real(kind=rk), intent(in), optional :: default
real(kind=rk), intent(in), optional :: minimum
real(kind=rk), intent(in), optional :: maximum
character(len=*), intent(in), optional :: description
Return Value class(type_real_setting), pointer
Calls
Called by
Contents
None
Call graph
type_real_setting_create calls report_error, real_set_data
real_set_data calls report_error
get_real2 calls type_real_setting_create