has_dimension – Fortran Program
has_dimension Function
10 statements
Source File
public function has_dimension(dimensions, id)
Arguments
Type Intent Optional Attributes Name
type(type_dimension_pointer), intent(in) :: dimensions(:)
integer, intent(in) :: id
Return Value logical
Called by
Contents
None
Call graph
field_has_dimension calls has_dimension
initialize calls has_dimension
single_text_file_with_1d_variable_write_header calls has_dimension