in_window – Fortran Program
in_window Function
5 statements
Source File
private function in_window(self, julianday, secondsofday, microseconds, n)
Arguments
Type Intent Optional Attributes Name
class(type_file), intent(in) :: self
integer, intent(in) :: julianday
integer, intent(in) :: secondsofday
integer, intent(in) :: microseconds
integer, intent(in) :: n
Return Value logical
Called by
Contents
None
Call graph
output_manager_save2 calls in_window
output_manager_prepare_save calls in_window
output_manager_save1 calls output_manager_save2
output_manager_save calls output_manager_save2, output_manager_save1