initialize – Fortran Program
initialize Subroutine
150 statements
Source File
private subroutine initialize(self)
Arguments
Type Intent Optional Attributes Name
class(type_netcdf_file), intent(inout) :: self
Calls
Contents
None
Call graph
initialize calls put_att_typed_real, nf90_put_att, check_err, nf90_enddef, write_time_string, nf90_create, nf90_def_var
put_att_typed_real calls nf90_put_att
check_err calls nf90_strerror