process_file – Fortran Program
process_file Subroutine
64 statements
Source File
private subroutine process_file(self, pair)
Arguments
Type Intent Optional Attributes Name
class(type_file_populator), intent(inout) :: self
type(type_key_value_pair), intent(inout) :: pair
Calls
Contents
None
Call graph
process_file calls type_settings_create, type_option, read_time_string, configure_group, output_manager_add_file, type_logical_setting_create