fabm_tracer_init – FABM in UVic
fabm_tracer_init Subroutine
GNU Free Documentation License
11 statements
Source File
public subroutine fabm_tracer_init(m)
surface boundary data are handled via sbc(imt,jmt,numsbc) in setmom.F, tracer.F, gosbc.F, embmio.F
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: m
number of handled variables handled so far
Calls
Source Code
      subroutine fabm_tracer_init(m)
         !! surface boundary data are handled via sbc(imt,jmt,numsbc) in
         !! setmom.F, tracer.F, gosbc.F, embmio.F
         integer, intent(inout) :: m
            !! number of handled variables handled so far
         integer :: n
         ! need to get mapt populated early - setmom() -> mom_rest_in()
         associate(VAR => model%interior_state_variables)
!KB         print*, 'AAA ', mapt
         do n = 1, size(model%interior_state_variables)
            mapt(m+n) = trim(VAR(n)%name)
            mapst(m+n-4) = 's'//trim(VAR(n)%name)
            itrc(m+n-4) = m+n
         end do
#if 0
         print*, 'AAA ',mapt
         print*, mapst
         stop 'kaj'
#endif
         end associate
      end subroutine fabm_tracer_init
Call graph
fabm_tracer_init calls interior_state_variables, itrc, mapst, mapt