fabm_configure – FABM in UVic
fabm_configure Subroutine
GNU Free Documentation License
36 statements
Source File
public subroutine fabm_configure(dt, yaml_file)
read fabm.yaml and call FABM configuration subroutines
Note
seems tmask is not initialised until called in mom() - i.e. after initialization - so all values are 0 here
Arguments
Type Intent Optional Attributes Name
real(kind=rke), intent(in) :: dt
bio-geochemical time step as set by MOM2 [s]
character(len=*), intent(in), optional :: yaml_file
name of alternativ FABM configuration file
Calls
Source Code
      subroutine fabm_configure(dt,yaml_file)
        !! read fabm.yaml and call FABM configuration subroutines
      real(rke), intent(in) :: dt
        !! bio-geochemical time step as set by MOM2 [s]
      character(len=*), intent(in), optional :: yaml_file
        !! name of alternativ FABM configuration file
        integer :: n
         print*, '==> Initializing FABM component with nt=',nt
         if (present(yaml_file)) then
            model => fabm_create_model(trim(yaml_file))
         else
            model => fabm_create_model('fabm.yaml')
         end if
         nsurface = size(model%surface_state_variables)
         npelagic = size(model%interior_state_variables)
         nbottom = size(model%bottom_state_variables)
         if (nt .ne. npelagic+2) then
            print*, 'nt (UVic)     = ',nt
            print*, 'nsurface      = ',nsurface
            print*, 'npelagic (+2) = ',npelagic+2
            print*, 'nbottom =       ',nbottom
            stop 'fabm_configure()'
         end if
#ifdef DEBUG
         print*, imt,jmt,jmw
         !print*, jrow,js,je,is,ie
         print*, 'zt: ',shape(zt)
         print*, 't: ',shape(t)
         print*, 'sbc: ',shape(sbc)
         print*, 'src: ',shape(src) ! imt,km,jsmw:jemw,nsrc
         print*, 'source: ',shape(source) ! imt,km,jsmw:jemw
         print*, 'rho: ',shape(rho)
         !stop 112
#endif
         call model%set_domain(imt,km,jmt,dt)
         call model%set_domain_start(2,1,2)
         call model%set_domain_stop(imt-1,km,jmt-1)
         call model%set_mask(tmask,tmask(:,1,:))
         call model%set_bottom_index(kmt)
         ! need to get mapt populated early - setmom() -> mom_rest_in()
         do n = 1, size(model%interior_state_variables)
            mapt(2+n) = trim(model%interior_state_variables(n)%name)
         end do
         !! @note
         !! seems tmask is not initialised until called in mom() -
         !! i.e. after initialization - so all values are 0 here
         !! @endnote
      end subroutine fabm_configure
Call graph
fabm_configure calls fabm_create_model, interior_state_variables, mapt, set_bottom_index, set_domain, set_domain_start, set_domain_stop, set_mask, tmask