fabm_link_data – FABM in UVic
fabm_link_data Subroutine
GNU Free Documentation License
21 statements
Source File
public subroutine fabm_link_data()
link all FABM configured external dependencies - and call model%start() to assure proper configuration
Arguments
None
Calls
Source Code
      subroutine fabm_link_data()
         !! link all FABM configured external dependencies - and call
         !! model%start() to assure proper configuration
         integer :: n
         ! link to time in-dependent data that do require transformation
         call link_grid()
         ! link to time dependent data that do NOT require transformation
         call model%link_interior_data(
     &        fabm_standard_variables%temperature,t(:,:,:,itemp,0))
         ! link to time dependent data that do require transformation
         ! initialize and update time changing environmental variables
         call link_wind()
         call link_mole_fraction_of_carbon_dioxide_in_air()
ckb         call link_surface_downwelling_photosynthetic_radiative_flux()
         call link_surface_swr_flux()
         call link_bottom_stress()
ckb         call link_downwelling_photosynthetic_radiative_flux()
         call link_salinity()
         call link_density()
         ! link to FABMs surface state variables
         do n = 1,nsurface
            ! call model%link_surface_state_data(n, sed(:,:,n))
         end do
         ! link to FABMs interior state variables
         do n = 1, size(model%interior_state_variables)
            call model%link_interior_state_data(n, t(:,:,:,2+n,0))
            itrc(n+2) = n+2
           !KBmapst(2+n) = 's'//trim(mapt(2+n))
         end do
         ! link to FABMs bottom state variables
         do n = 1,nbottom
            call model%link_bottom_state_data(n, sed(:,:,n))
         end do
         call model%start()
      end subroutine fabm_link_data
Call graph
fabm_link_data calls itrc, link_bottom_state_data, link_interior_data, link_interior_state_data, link_bottom_stress, link_density, link_grid, link_mole_fraction_of_carbon_dioxide_in_air, link_salinity, link_surface_swr_flux, link_wind, sed, start, t
link_bottom_stress calls get_horizontal_variable_id, link_horizontal_data, variable_needs_values
link_density calls link_interior_data, get_interior_variable_id, variable_needs_values
link_grid calls link_interior_data, dzt, kmt, zt
link_mole_fraction_of_carbon_dioxide_in_air calls get_horizontal_variable_id, link_horizontal_data, variable_needs_values
link_salinity calls link_interior_data, get_interior_variable_id, variable_needs_values
link_surface_swr_flux calls get_horizontal_variable_id, link_horizontal_data, variable_needs_values
link_wind calls get_horizontal_variable_id, link_horizontal_data, variable_needs_values