fabm_rest_in – FABM in UVic
fabm_rest_in Subroutine
GNU Free Documentation License
27 statements
Source File
public subroutine fabm_rest_in(iou, ln, ib, ic, tmpik, ils, ile, kls, kle, tau)
reading FABM restart variables from NetCDF
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iou
NetCDF file id
integer, intent(in) :: ln
data length
integer, intent(in) :: ib(:)
array of start indices
integer, intent(in) :: ic(:)
array of counts
real, intent(inout) :: tmpik(ils:ile,kls:kle)
array for present data slice
integer, intent(in) :: ils
start index - i
integer, intent(in) :: ile
end index - i
integer, intent(in) :: kls
start index - k
integer, intent(in) :: kle
end index - k
integer, intent(in) :: tau
time index - -1:1
Calls
Source Code
      subroutine fabm_rest_in(iou,ln,ib,ic,tmpik,ils,ile,kls,kle,tau)
         !! reading FABM restart variables from NetCDF
      integer, intent(in) :: iou
         !! NetCDF file id
      integer, intent(in) :: ln
         !! data length
      integer, intent(in) :: ib(:)
         !! array of start indices
      integer, intent(in) :: ic(:)
         !! array of counts
      real, intent(inout) :: tmpik(ils:ile,kls:kle)
         !! array for present data slice
      integer, intent(in) :: ils
         !! start index - i
      integer, intent(in) :: ile
         !! end index - i
      integer, intent(in) :: kls
         !! start index - k
      integer, intent(in) :: kle
         !! end index - k
      integer, intent(in) :: tau
         !! time index - -1:1
         real, parameter :: c0 = 0.
         real, parameter :: c1 = 1.
         character(1) :: x
            ! to distinguise between tau and taup1
         integer :: j
            ! j row slice
         integer :: n
            ! counter
         if (tau == 0) x = '1'
         if (tau == 1) x = '2'
         j = ib(2)
         associate(VAR => model%interior_state_variables)
         do n=1,npelagic
            tmpik(ils:ile,kls:kle) = t(ils:ile,kls:kle,j,n,tau)
            call getvara(trim(VAR(n)%name)//x, iou, ln, ib, ic,
     &                   tmpik, c1, c0)
            t(ils:ile,kls:kle,j,n,tau) = tmpik(ils:ile,kls:kle)
         end do
         end associate
      end subroutine fabm_rest_in
Call graph
fabm_rest_in calls getvara, interior_state_variables, t