link_wind – FABM in UVic
link_wind Subroutine
GNU Free Documentation License
10 statements
Source File
private subroutine link_wind()
get wind speed FABM standard variable and if needed by FABM allocate memory
Arguments
None
Calls
Called by
Source Code
      subroutine link_wind()
         !! get wind speed FABM standard variable and if needed by FABM
         !! allocate memory
         integer rc
            ! status variable
         id_windspeed = model%get_horizontal_variable_id(
     &                  standard_variables%wind_speed)
         if (model%variable_needs_values(id_windspeed)) then
            allocate(windspeed(imt,jmt),stat=rc)
            if (rc /= 0) stop
     &              'link_wind(): Error allocating (windspeed)'
            windspeed = 0._rke
            call model%link_horizontal_data(id_windspeed,windspeed)
         end if
      end subroutine link_wind
Call graph
link_wind calls get_horizontal_variable_id, link_horizontal_data, variable_needs_values
fabm_link_data calls link_wind