link_surface_downwelling_photosynthetic_radiative_flux – FABM in UVic
link_surface_downwelling_photosynthetic_radiative_flux Subroutine
GNU Free Documentation License
10 statements
Source File
private subroutine link_surface_downwelling_photosynthetic_radiative_flux()
Arguments
None
Calls
Called by
Call graph
link_surface_downwelling_photosynthetic_radiative_flux calls get_horizontal_variable_id, link_horizontal_data, variable_needs_values
fabm_link_data calls link_surface_downwelling_photosynthetic_radiative_flux