link_downwelling_photosynthetic_radiative_flux – FABM in UVic
link_downwelling_photosynthetic_radiative_flux Subroutine
GNU Free Documentation License
10 statements
Source File
private subroutine link_downwelling_photosynthetic_radiative_flux()
get salinity FABM standard variable and if needed by FABM allocate memory
Arguments
None
Calls
Called by
Call graph
link_downwelling_photosynthetic_radiative_flux calls get_interior_variable_id, link_interior_data, variable_needs_values
fabm_link_data calls link_downwelling_photosynthetic_radiative_flux