update_data – FABM in UVic
update_data Subroutine
GNU Free Documentation License
9 statements
Source File
private subroutine update_data(joff)
update all time varying FABM configured external dependencie !s by calling individual update routines - tests done in routin !es
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: joff
offset row in global window
Calls
Called by
Source Code
      subroutine update_data(joff)
         !! update all time varying FABM configured external dependencies
         !! by calling individual update routines - tests done in routines
         integer, intent(in) :: joff
            !! offset row in global window
         ! dic, carbon_14, alk, n03, 02, n2?
         call update_wind()
         call update_mole_fraction_of_carbon_dioxide_in_air()
c         call update_surface_downwelling_photosynthetic_radiative_flux()
         call update_surface_swr_flux()
         call update_bottom_stress(joff)
c         call update_downwelling_photosynthetic_radiative_flux()
         call update_salinity()
         call update_density()
      end subroutine update_data
Call graph
update_data calls update_bottom_stress, update_density, update_mole_fraction_of_carbon_dioxide_in_air, update_salinity, update_surface_swr_flux, update_wind
update_bottom_stress calls bmf, kmt, variable_needs_values
update_density calls kmt, rho, variable_needs_values
update_mole_fraction_of_carbon_dioxide_in_air calls kmt, variable_needs_values
update_salinity calls kmt, t, variable_needs_values
update_surface_swr_flux calls dnswr, kmt
update_wind calls kmt, sbc, variable_needs_values
fabm_update calls update_data