update_downwelling_photosynthetic_radiative_flux – FABM in UVic
update_downwelling_photosynthetic_radiative_flux Subroutine
GNU Free Documentation License
14 statements
Source File
private subroutine update_downwelling_photosynthetic_radiative_flux()
calculate salinity in PSU according to
Arguments
None
Calls
Source Code
      subroutine update_downwelling_photosynthetic_radiative_flux()
         !! calculate salinity in PSU according to $$S = 35 + 1000*S_{UVic}$$
         integer i,j,k
            ! local loop counters
         if (model%variable_needs_values(
     &        id_downwelling_photosynthetic_radiative_flux)) then
            do j=2,jmt-1
               do k=1,km
                  do i=2,imt-1
                     if (kmt(i,j) > 0) then
                        downwelling_photosynthetic_radiative_flux(i,k,j)
     &                     = 35._rk+1000._rke*t(i,k,j,isalt,0)
                     end if
                  end do
               end do
            end do
         end if
      end subroutine update_downwelling_photosynthetic_radiative_flux
Call graph
update_downwelling_photosynthetic_radiative_flux calls kmt, t, variable_needs_values