update_bottom_stress – FABM in UVic
update_bottom_stress Subroutine
GNU Free Documentation License
15 statements
Source File
private subroutine update_bottom_stress(joff)
calculate the bottom stress in Pa
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: joff
offset row in global window
Calls
Called by
Source Code
      subroutine update_bottom_stress(joff)
         !! calculate the bottom stress in Pa
      integer, intent(in) :: joff
         !! offset row in global window
         real(rke), parameter :: x=10._rke
            !! dynes/cm2 --> Pa
         integer i,j,jrow
            ! local loop counters
         if (model%variable_needs_values(id_bottom_stress)) then
            do j=2,jmt-1
               jrow = j+joff
               do i=2,imt-1
                  if (kmt(i,jrow) > 0) then
                     bottom_stress(i,j) = x*sqrt(
     &                      bmf(i,jrow,1)**2 + bmf(i,jrow,2)**2)
                  end if
               end do
            end do
         end if
      end subroutine update_bottom_stress
Call graph
update_bottom_stress calls bmf, kmt, variable_needs_values
update_data calls update_bottom_stress
fabm_update calls update_data